// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NlbUIClient is the client API for NlbUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NlbUIClient interface {
	// ListEngineSpecs returns a list of Load Balancer Engine(s) that can be started through the UI.
	ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (NlbUI_ListEngineSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type nlbUIClient struct {
	cc grpc.ClientConnInterface
}

func NewNlbUIClient(cc grpc.ClientConnInterface) NlbUIClient {
	return &nlbUIClient{cc}
}

func (c *nlbUIClient) ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (NlbUI_ListEngineSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &NlbUI_ServiceDesc.Streams[0], "/v1.NlbUI/ListEngineSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &nlbUIListEngineSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type NlbUI_ListEngineSpecsClient interface {
	Recv() (*ListEngineSpecsResponse, error)
	grpc.ClientStream
}

type nlbUIListEngineSpecsClient struct {
	grpc.ClientStream
}

func (x *nlbUIListEngineSpecsClient) Recv() (*ListEngineSpecsResponse, error) {
	m := new(ListEngineSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *nlbUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.NlbUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NlbUIServer is the server API for NlbUI service.
// All implementations must embed UnimplementedNlbUIServer
// for forward compatibility
type NlbUIServer interface {
	// ListEngineSpecs returns a list of Load Balancer Engine(s) that can be started through the UI.
	ListEngineSpecs(*ListEngineSpecsRequest, NlbUI_ListEngineSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedNlbUIServer()
}

// UnimplementedNlbUIServer must be embedded to have forward compatible implementations.
type UnimplementedNlbUIServer struct {
}

func (UnimplementedNlbUIServer) ListEngineSpecs(*ListEngineSpecsRequest, NlbUI_ListEngineSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEngineSpecs not implemented")
}
func (UnimplementedNlbUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedNlbUIServer) mustEmbedUnimplementedNlbUIServer() {}

// UnsafeNlbUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NlbUIServer will
// result in compilation errors.
type UnsafeNlbUIServer interface {
	mustEmbedUnimplementedNlbUIServer()
}

func RegisterNlbUIServer(s grpc.ServiceRegistrar, srv NlbUIServer) {
	s.RegisterService(&NlbUI_ServiceDesc, srv)
}

func _NlbUI_ListEngineSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEngineSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NlbUIServer).ListEngineSpecs(m, &nlbUIListEngineSpecsServer{stream})
}

type NlbUI_ListEngineSpecsServer interface {
	Send(*ListEngineSpecsResponse) error
	grpc.ServerStream
}

type nlbUIListEngineSpecsServer struct {
	grpc.ServerStream
}

func (x *nlbUIListEngineSpecsServer) Send(m *ListEngineSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _NlbUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NlbUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.NlbUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NlbUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NlbUI_ServiceDesc is the grpc.ServiceDesc for NlbUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NlbUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.NlbUI",
	HandlerType: (*NlbUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _NlbUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEngineSpecs",
			Handler:       _NlbUI_ListEngineSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "nlb-ui.proto",
}
